PIKA_RESPONSE_STATUS_SUCCESS = "SUCCESS"
PIKA_RESPONSE_STATUS_FAILURE = "FAILED"
PIKA_RESPONSE_STATUS_ACCEPTED = "ACCEPTED"

PIKA_CAMPAIGN_STATUS_CODES = ['INITIALIZED', 'LOADING', 'READY', 'CONSUMED']

REPORT_DATE_PARAM_6_MONTH = 'LAST_6_MONTHS'

TAGS_CONSUMER_SEGMENT_TYPE = 'Consumer Segment'

####API PARAMTERS

API_CUSTOMER_SEGMENT_KPIS = ['total_consumer_count', 'new_consumer_count']

API_DATE_AGGREGATION_LEVEL = {"CURRENT_WEEK": "daily", "PREVIOUS_WEEK": "daily", "CURRENT_MONTH": "daily",
                              "PREVIOUS_MONTH": "daily"
    , "LAST_3_MONTHS": "weekly", "LAST_6_MONTHS": "weekly"}

######ALL REAL TIME RELATED CONSTANTS######
PIKA_EVENT_TYPES = ['checkin', 'register', 'purchase', 'redeem']
PIKA_EVENT_TYPE_CHECKIN = 'checkin'
PIKA_EVENT_TYPE_REGISTRATION = 'register'
PIKA_EVENT_TYPE_PURCHASE = 'purchase'
PIKA_EVENT_TYPE_REDEEM = 'redeem'

CELERY_EVENT_QUE_NAME = 'testing'
CELERY_EVENT_MODULE_NAME = 'events'
CELERY_EVENT_TASK_CHECKIN = 'checkin'

#### DATABASE CONSTANTS

REPORT_DB_DATE_FORMAT = '%Y-%m-%d'
